### ISSUE TITLE
Merge DesignLibrary vignettes into book

### ISSUE THREAD

**Issue by jaspercooper** [DeclareDesign/book#3]
- [ ] binary_iv.Rmd
- [x] block_cluster_two_arm.Rmd
- [x] cluster_sampling.Rmd
- [ ] factorial.Rmd
- [ ] mediation_analysis.Rmd
- [ ] multi_arm.Rmd
- [ ] pretest_posttest.Rmd
- [ ] process_tracing.Rmd
- [x] randomized_response.Rmd
- [ ] regression_discontinuity.Rmd
- [ ] spillover.Rmd
- [ ] two_arm_attrition.Rmd
- [ ] two_arm.Rmd
- [ ] two_by_two.Rmd

**Comment by graemeblair** [comment]
I'm closing this because we decided those writing vignettes will bring in what they want from design library and other previous work.
